# N = 2 - Latin Squares

In [38]:
import Pkg;
Pkg.activate("ndoku-julia/")

using Combinatorics
using DataStructures
using JLD2
using Oscar

  Activating project at `/mnt/raid/dev/data-projects/ndoku-julia/ndoku-julia`


In [2]:
const n = 2
const N = n ^ 2
n2_adj_mtx = JLD2.load("data/n2_data.jld2", "adj_mtx")

24×24 Matrix{Bool}:
 0  0  0  0  0  0  0  1  0  1  1  0  0  1  0  0  1  1  1  0  0  0  1  1
 0  0  0  0  0  0  1  0  1  0  0  1  1  0  0  0  1  1  0  1  0  0  1  1
 0  0  0  0  0  0  0  1  0  0  1  1  0  1  0  1  1  0  0  1  1  1  0  0
 0  0  0  0  0  0  1  0  0  0  1  1  1  0  1  0  0  1  1  0  1  1  0  0
 0  0  0  0  0  0  1  0  1  1  0  0  0  1  1  1  0  0  0  1  0  1  1  0
 0  0  0  0  0  0  0  1  1  1  0  0  1  0  1  1  0  0  1  0  1  0  0  1
 0  1  0  1  1  0  0  0  0  0  0  0  0  0  0  1  1  1  0  0  1  0  1  1
 1  0  1  0  0  1  0  0  0  0  0  0  0  0  1  0  1  1  0  0  0  1  1  1
 0  1  0  0  1  1  0  0  0  0  0  0  0  1  0  1  0  1  1  1  0  1  0  0
 1  0  0  0  1  1  0  0  0  0  0  0  1  0  1  0  1  0  1  1  1  0  0  0
 ⋮              ⋮              ⋮              ⋮              ⋮        
 0  0  1  0  1  1  1  0  1  0  1  0  0  0  0  0  0  0  1  1  0  0  1  0
 1  1  1  0  0  0  1  1  0  1  0  0  0  0  0  0  0  0  1  0  0  1  0  1
 1  1  0  1  0  0  1  1  1  0  0  0  0  0  0 

In [3]:
function is_latin_square(adj_mtx, subset)
    check_vect = map(comb -> adj_mtx[comb...], combinations(subset, 2))
    check_vect == ones(Bool, binomial(N, 2))
end;

function find_latin_squares(adj_mtx)
    subsets = combinations(1:first(size(adj_mtx)), N)
    filter(x -> is_latin_square(adj_mtx, x), collect(subsets))
end;

@time latin_square_ids = find_latin_squares(n2_adj_mtx)
@show length(latin_square_ids) * factorial(N)
latin_square_ids

  0.493663 seconds (884.41 k allocations: 38.232 MiB, 93.75% compilation time)
length(latin_square_ids) * factorial(N) = 576


24-element Vector{Vector{Int64}}:
 [1, 8, 17, 24]
 [1, 8, 18, 23]
 [1, 10, 17, 19]
 [1, 11, 14, 24]
 [2, 7, 17, 24]
 [2, 7, 18, 23]
 [2, 9, 18, 20]
 [2, 12, 13, 23]
 [3, 8, 17, 22]
 [3, 11, 14, 22]
 ⋮
 [4, 12, 15, 19]
 [5, 7, 16, 23]
 [5, 9, 14, 22]
 [5, 9, 16, 20]
 [5, 10, 15, 20]
 [6, 8, 15, 24]
 [6, 9, 16, 19]
 [6, 10, 13, 21]
 [6, 10, 15, 19]

In [4]:
n2_dist_mtx = JLD2.load("data/n2_data.jld2", "dist_mtx")

24×24 Matrix{Int64}:
 4  2  2  1  1  2  2  0  1  0  0  1  1  0  2  1  0  0  0  1  1  2  0  0
 2  4  1  2  2  1  0  2  0  1  1  0  0  1  1  2  0  0  1  0  2  1  0  0
 2  1  4  2  2  1  1  0  2  1  0  0  2  0  1  0  0  1  1  0  0  0  1  2
 1  2  2  4  1  2  0  1  1  2  0  0  0  2  0  1  1  0  0  1  0  0  2  1
 1  2  2  1  4  2  0  1  0  0  2  1  1  0  0  0  1  2  2  0  1  0  0  1
 2  1  1  2  2  4  1  0  0  0  1  2  0  1  0  0  2  1  0  2  0  1  1  0
 2  0  1  0  0  1  4  2  2  1  1  2  2  1  1  0  0  0  1  2  0  1  0  0
 0  2  0  1  1  0  2  4  1  2  2  1  1  2  0  1  0  0  2  1  1  0  0  0
 1  0  2  1  0  0  2  1  4  2  2  1  1  0  2  0  1  0  0  0  1  0  2  1
 0  1  1  2  0  0  1  2  2  4  1  2  0  1  0  2  0  1  0  0  0  1  1  2
 ⋮              ⋮              ⋮              ⋮              ⋮        
 1  2  0  1  0  0  0  1  0  2  0  1  1  2  2  4  1  2  0  0  1  2  0  1
 0  0  0  1  1  2  0  0  1  0  2  1  1  2  2  1  4  2  0  1  1  0  2  0
 0  0  1  0  2  1  0  0  0  1  1  2  2  1  1

In [5]:
function subset_distance(dist_mtx, subset)
    sum(map(comb -> dist_mtx[comb...], combinations(subset, 2)))
end;

function subsets_distance(dist_mtx)
    subsets = combinations(1:first(size(dist_mtx)), N)
    map(x -> subset_distance(dist_mtx, x), collect(subsets))
end;

@time subset_distances = subsets_distance(n2_dist_mtx)
@show sum(subset_distances .== 0)
subset_distances

  0.200111 seconds (544.86 k allocations: 21.875 MiB, 88.99% compilation time)
sum(subset_distances .== 0) = 24


10626-element Vector{Int64}:
 10
 10
  9
  8
  7
  8
  7
  6
  6
  8
  ⋮
  9
 10
 10
  9
 10
  9
  9
 10
 10

In [6]:
sc = simplicial_complex(latin_square_ids)
h_vector(sc)

5-element Vector{Int64}:
   1
  20
  42
 -52
  13

In [7]:
subset_perms = permutations(1:24, 4)
pair_ids = combinations(1:4, 2)

incl_excl_mtx = map(it -> !n2_adj_mtx[it[1][it[2][1]], it[1][it[2][2]]], Iterators.product(subset_perms, pair_ids))

255024×6 Matrix{Bool}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  0  1
 1  1  0  1  1  0
 1  1  1  1  0  1
 1  1  0  1  1  1
 1  1  0  1  1  0
 1  1  1  1  0  0
 1  1  1  1  0  1
 ⋮              ⋮
 1  1  1  1  0  0
 1  1  0  1  1  0
 1  1  0  1  1  1
 1  1  1  1  0  1
 1  1  0  1  1  0
 1  1  1  1  0  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

In [46]:
function invalid_subset_count(invalid_pair_position_mtx)
    total = 0

    for l in 1:6
        l_count = 0
        combs = collect(combinations(1:4, 2))

        for comb in combinations(1:6, l)
            res = ones(Bool, first(size(invalid_pair_position_mtx)))
            
            for col in eachcol(invalid_pair_position_mtx[:, comb])
                res = res .& col
            end

            subtotal = sum(res)
            l_count += subtotal

            # The distribution of all that has to do with the multiset 
            # permutations for the selection of pairs of positions
            # The counts seem to fall pretty well into the categories of them
            # with some counts being the same for different categories

            # See the counts by uncommenting below
            # @show (counter(vcat(combs[comb]...)), subtotal)        
        end

        total += l_count * (-1) ^ (l-1)
    end

    total
end;

incl_excl_invalid = invalid_subset_count(incl_excl_mtx)
latin_squares_by_incl_excl = binomial(24, 4) * factorial(4) - incl_excl_invalid
        

576