# Experiments in Tiling versions of Sudoku

## Description

In this one we will play around with non-square sudoku grids and non-uniform polyomino tilings for the blocks

In [1]:
import Pkg;
Pkg.activate("ndoku-julia/")

using Combinatorics
using DataStructures
using JLD2
using Oscar
using StatsBase

  Activating project at `/mnt/raid/dev/data-projects/ndoku-julia/ndoku-julia`


In [15]:
# tiling_matrix = [1 1 2 3 3; 1 2 2 2 3; 1 1 2 4 3; 5 5 5 4 3; 5 5 4 4 4]
# tiling_matrix = [1 1 2 3 3; 1 2 2 2 3; 1 5 2 4 3; 1 5 5 4 3; 5 5 4 4 4]
tiling_matrix = [1 1 2 2 2; 3 1 1 2 2; 3 1 4 5 5; 3 3 4 4 5; 3 4 4 5 5]

5×5 Matrix{Int64}:
 1  1  2  2  2
 3  1  1  2  2
 3  1  4  5  5
 3  3  4  4  5
 3  4  4  5  5

In [16]:
function generate_perm_matrix(perm)
    res = zeros(Bool, (5,5))

    for i in 1:5
        res[i, perm[i]] = true
    end

    res
end;

function is_valid_tiling_perm(tiling::Matrix{Int}, perm::Matrix{Bool})
    iszero(setdiff(1:5, tiling[perm]))
end;

perms = collect(permutations(1:5))
perms_as_matrix = generate_perm_matrix.(perms)
tiling_valid_filter = is_valid_tiling_perm.((tiling_matrix,), perms_as_matrix)

@show sum(tiling_valid_filter)
@show StatsBase.countmap(first.(perms[tiling_valid_filter]))

perms[tiling_valid_filter]


sum(tiling_valid_filter) = 33
StatsBase.countmap(first.(perms[tiling_valid_filter])) = Dict(5 => 6, 4 => 10, 2 => 10, 3 => 3, 1 => 4)


33-element Vector{Vector{Int64}}:
 [1, 4, 3, 2, 5]
 [1, 4, 5, 2, 3]
 [1, 5, 3, 2, 4]
 [1, 5, 4, 2, 3]
 [2, 4, 1, 3, 5]
 [2, 4, 1, 5, 3]
 [2, 4, 3, 1, 5]
 [2, 4, 3, 5, 1]
 [2, 4, 5, 1, 3]
 [2, 4, 5, 3, 1]
 ⋮
 [4, 2, 5, 3, 1]
 [4, 3, 1, 5, 2]
 [4, 3, 5, 1, 2]
 [5, 1, 2, 3, 4]
 [5, 2, 1, 3, 4]
 [5, 2, 3, 1, 4]
 [5, 2, 4, 1, 3]
 [5, 2, 4, 3, 1]
 [5, 3, 4, 1, 2]

In [17]:
function tiling_valid_solutions(valid_perms)
    combs = collect(combinations(valid_perms, 5))

    valid_combs = filter( comb -> sum(comb) == ones(Int, (5, 5)), combs)
    solution_matrix_view.(valid_combs)
end;

function solution_matrix_view(combination)
    sum(.*(combination, 1:5))
end;

valid_solutions = tiling_valid_solutions(perms_as_matrix[tiling_valid_filter])
@show length(valid_solutions)
sample(valid_solutions)


length(valid_solutions) = 17


5×5 Matrix{Int64}:
 1  2  3  4  5
 3  5  4  1  2
 4  3  5  2  1
 5  1  2  3  4
 2  4  1  5  3

## Notes for future self
- make more general 
- figure out a way to get tilings relatively effectively
- look into the stats of valid solutions of the same size across tilings
    - use the 4x4 case (manual tilings) as the first test bed
    - how many tilings are each latin square valid in?